### ISSUE TITLE
Error with Imageloader TFT Gizmo Example

### ISSUE THREAD

**Issue by djecken** [adafruit/Adafruit_Arcada#15]
Testing out imageloader TFT gizmo demo code with Circuit Playground Express on Arduino 1.8 with latest libraries. Getting the following error when compiling to board.

`/Users/pedroruiz/Documents/Arduino/libraries/Adafruit_Arcada_Library/Adafruit_Arcada.cpp: In member function 'void Adafruit_Arcada_SPITFT::timerStop()':
/Users/pedroruiz/Documents/Arduino/libraries/Adafruit_Arcada_Library/Adafruit_Arcada.cpp:323:3: error: 'zerotimer' was not declared in this scope
   zerotimer.enable(false);
   ^
exit status 1
Error compiling for board Adafruit Circuit Playground Express.`

**Comment by makermelissa** [comment]
Do you have the Adafruit ZeroTimer library installed? See https://learn.adafruit.com/adafruit-tft-gizmo/arcada-libraries

**Comment by djecken** [comment]
Yes, I currently have the 2.0.3 zero timer library installed. Using adafruit arcada 2.1.4 version from the arduino library manager. maybe its not that latest?

**Comment by makermelissa** [comment]
That's the latest. I just tried recompiling with both CPB and CPX selected and both compiled without issues.

**Comment by makermelissa** [comment]
Oops, my libraries were out of date. Updating them to the latest caused it to fail.

**Comment by makermelissa** [comment]
Changing to Arcada 2.1.3 and TinyUSB 0.6.0 fixes this, so those updates broke something.

**Comment by ladyada** [comment]
@makermelissa please work on the tft guides, i will take care of this

**Comment by djecken** [comment]
OK confirmed TFT gizmo demo code works with arcada 2.1.3 and tinyUSB 0.6 , thanks!

**Comment by caternuson** [comment]
Looks like this is same or at least related:
https://forums.adafruit.com/viewtopic.php?f=19&t=157375#p775840

**Comment by VirgilMachine1** [comment]
The hallowing problem is mine.  Reverting to 2.1.3 version of the arcada librsry allowed a clean compile

**Comment by ladyada** [comment]
commited fix to master, updating travis to catch compile errors for cplays

**Comment by VirgilMachine1** [comment]
hallowingmo_acrcadatest still does not compile with the 2.1.4 version...same error.

**Comment by ladyada** [comment]
hold tight :) 2.1.5 coming soon

**Comment by ladyada** [comment]
ok try 2.1.5 when it comes out!

**Comment by VirgilMachine1** [comment]
Version 2.1.6 fixed it

**Comment by The-Btec** [comment]
Im having the same problem as well. Tried older libraries for zero, tinyusb, and arcada. I have CPX selected as my board, usbtiny as stack and comp port selected. Is there a specific programmer that is supposed to be used? I ran into wrong programmer issue on one of my other boards is why i ask.

**Comment by The-Btec** [comment]
Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "Adafruit Circuit Playground Express, TinyUSB, Off"

Multiple libraries were found for "Adafruit_GFX.h"
In file included from C:\Users\Smyrna Pawn\Documents\Arduino\libraries\Adafruit_Arcada_Library/arcadatype.h:7:0,

 Used: C:\Users\Smyrna Pawn\Documents\Arduino\libraries\Adafruit_GFX_Library
 Not used: C:\Users\Smyrna Pawn\Documents\Arduino\libraries\Adafruit-GFX-Library-master
Multiple libraries were found for "Adafruit_ZeroDMA.h"
                 from C:\Users\Smyrna Pawn\Documents\Arduino\libraries\Adafruit_Arcada_Library/Adafruit_Arcada_CircuitPlaygroundExpress.h:26,

 Used: C:\Users\Smyrna Pawn\Documents\ArduinoData\packages\adafruit\hardware\samd\1.5.7\libraries\Adafruit_ZeroDMA
 Not used: C:\Users\Smyrna Pawn\Documents\Arduino\libraries\Adafruit_Zero_DMA_Library
                 from C:\Users\Smyrna Pawn\Documents\Arduino\libraries\Adafruit_Arcada_Library/Adafruit_Arcada.h:26,

Multiple libraries were found for "Adafruit_CircuitPlayground.h"
 Used: C:\Users\Smyrna Pawn\Documents\Arduino\libraries\Adafruit_Circuit_Playground
 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\libraries\Adafruit_Circuit_Playground
                 from C:\Users\Smyrna Pawn\Downloads\imageloader_tft_gizmo\imageloader_tft_gizmo.ino:1:

C:\Users\Smyrna Pawn\Documents\Arduino\libraries\Adafruit_ImageReader_Library/Adafruit_ImageReader.h:20:10: fatal error: Adafruit_EPD.h: No such file or directory

 #include "Adafruit_EPD.h"

          ^~~~~~~~~~~~~~~~

compilation terminated.

exit status 1
Error compiling for board Adafruit Circuit Playground Express.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by makermelissa** [comment]
@The-Btec please try installing Adafruit EPD as well and trying again.

**Comment by The-Btec** [comment]
@makermelissa I got it working. Thank you. Also learned a little from your suggestion based on error msg. Im new but DETERMINED to get this stuff. Lol. Thanks again

**Comment by ladyada** [comment]
@makermelissa imagereader shouldn't depend on EPD, please make a new sub-class/file imagereader_epd so that EPD does not become a direct dependency

**Comment by makermelissa** [comment]
Ok, good idea.
